Failure # 1 (occurred at 2025-06-27_13-33-28)
The actor died because of an error raised in its creation task, [36mray::DQN.__init__()[39m (pid=31756, ip=127.0.0.1, actor_id=520499432cab97f0ca380bdd01000000, repr=DQN(env=CityLearnMulti; env-runners=0; learners=0; multi-agent=False))
  File "python\\ray\\_raylet.pyx", line 1897, in ray._raylet.execute_task
  File "python\\ray\\_raylet.pyx", line 1837, in ray._raylet.execute_task.function_executor
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\_private\function_manager.py", line 689, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\util\tracing\tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 536, in __init__
    super().__init__(
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\tune\trainable\trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\util\tracing\tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\algorithms\dqn\dqn.py", line 611, in setup
    super().setup(config)
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 644, in setup
    self.env_runner_group = EnvRunnerGroup(
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\env\env_runner_group.py", line 198, in __init__
    self._setup(
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\env\env_runner_group.py", line 292, in _setup
    self._local_env_runner = self._make_worker(
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\env\env_runner_group.py", line 1294, in _make_worker
    return self.env_runner_cls(**kwargs)
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\env\single_agent_env_runner.py", line 106, in __init__
    self.make_env()
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\ray\rllib\env\single_agent_env_runner.py", line 677, in make_env
    gym.make_vec(
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\gymnasium\envs\registration.py", line 918, in make_vec
    env = gym.vector.SyncVectorEnv(
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\gymnasium\vector\sync_vector_env.py", line 86, in __init__
    self.envs = [env_fn() for env_fn in env_fns]
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\gymnasium\vector\sync_vector_env.py", line 86, in <listcomp>
    self.envs = [env_fn() for env_fn in env_fns]
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\gymnasium\envs\registration.py", line 903, in create_single_env
    single_env = make(env_spec, **env_spec_kwargs.copy())
  File "C:\Users\johann\anaconda3\envs\citylearn\lib\site-packages\gymnasium\envs\registration.py", line 740, in make
    env = env_creator(**env_spec_kwargs)
  File "c:\Users\johann\Documents\Studium\Bachelorarbeit\CityLearn_repo\examples\dqn_agent.py", line 25, in make_citylearn_env
    return RLlibMultiAgentEnv(env_config)
  File "C:\Users\johann\Documents\Studium\Bachelorarbeit\CityLearn_repo\citylearn\wrappers.py", line 809, in __init__
    env = RLlibMultiAgentObservationWrapper(env)
  File "C:\Users\johann\Documents\Studium\Bachelorarbeit\CityLearn_repo\citylearn\wrappers.py", line 679, in __init__
    assert not env.central_agent, 'RLlibMultiAgentObservationWrapper is'\
AttributeError: 'RLlibMultiAgentActionWrapper' object has no attribute 'central_agent'
